config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'creators'
  
  authenticate :admin do
    mount Avo::Engine, at: Avo.configuration.root_path
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "static_pages#home"

  get '/comparaisons', to: 'comparator_posts#show', as: 'comparaisons'
  get "/comparaison/:id", to: "comparator_posts#index", as: "comparator_post"
  get '/random', to: 'comparator_posts#random', as: 'comparaison_random'
  get '/settings', to: 'static_pages#settings', as: 'settings'
  get '/about', to: 'static_pages#about', as: 'about'

  get '/contact', to: 'static_pages#contact', as: "contact"
  get '/legal', to: 'static_pages#legal', as: "legal"
  get '/support', to: 'static_pages#support', as: "support"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comparator_post.rb
class ComparatorPost < ApplicationRecord
  paginates_per 8

  has_one_attached :illustration
  has_many_attached :trix_attachments
  
  validate :check_file_presence
  validates :title, :body, :author, :abstract, presence: true

  def check_file_presence
    errors.add(:illustration, "no file added") unless illustration.attached?
  end
end

app/models/support.rb
class Support < ApplicationRecord
  has_one_attached :illustration

  validate :check_file_presence
  validates :title, :body, :link, :active, presence: true

  def check_file_presence
    errors.add(:illustration, "no file added") unless illustration.attached?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/avo/comparator_posts_controller.rb
# This controller has been generated to enable Rails' resource routes.
# You shouldn't need to modify it in order to use Avo.
class Avo::ComparatorPostsController < Avo::ResourcesController
end

app/controllers/avo/supports_controller.rb
# This controller has been generated to enable Rails' resource routes.
# You shouldn't need to modify it in order to use Avo.
class Avo::SupportsController < Avo::ResourcesController
end

app/controllers/comparator_posts_controller.rb
class ComparatorPostsController < ApplicationController
  def show
    @comparators = ComparatorPost.order(created_at: :desc).page(params_permit_show[:page])
  end

  def random
    @comparator = ComparatorPost.all.sample(1).first
  end

  def index
    @comparator = ComparatorPost.find(params_permit_index[:id])
  end

  private
  def params_permit_show
    params.permit(:page)
  end

  def params_permit_index
    params.permit(:id)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
   @comparators = ComparatorPost.order(created_at: :desc)[..3]
  end

  def about
  end

  def settings
  end

  def legal

  end

  def contact

  end

  def support
    @supports = Support.where(active: true)
  end
end

app/controllers/supports_controller.rb
class SupportsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comparator_posts_helper.rb
module ComparatorPostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/supports_helper.rb
module SupportsHelper
end

app/views/comparator_posts/_comparator.html.erb
<div class="mb-[25px]">
  <div class="max-w-full max-h-[450px] w-full h-[450px]">
    <%= image_tag comparator.illustration, class: "w-full h-full object-cover rounded-md" %>
  </div>
  <%= link_to comparator do %>
  <div class="bg-[#f6f4f0] relative mt-[-150px] max-w-[90%] mx-auto pt-[40px] md:pt-[60px] px-[25px] md:px-[40px] pb-[20px] rounded-md drop-shadow-md">
    <div class="font-medium text-[#bbbac0] flex flex-row items-center text-[13px] md:text-[15px] text-center">
      <p class="mr-[7px]"><%= comparator.author %></p>
      <span class="w-[15px] h-[3px] bg-[#bbbac0] block rounded-full"></span>
      <p class="mx-[7px]"><%= l comparator.updated_at, :format => :short %></p>
    </div>
    <p class="mt-[20px] text-[#292a40] font-bold text-3xl md:text-[40px]"><%= comparator.title%></p>
    <p class="mt-[20px] text-justify"><%= comparator.abstract %></p>  
  </div>
   <% end %>
</div>

app/views/comparator_posts/_comparators.html.erb
<div>
  <div class="">
  <% comparators.each do |comparator| %>
    <%= render partial: "comparator_posts/comparator", locals: {comparator: comparator }%>
  <% end %>
  </div>
</div>

app/views/comparator_posts/_little_comparator.html.erb
<%= link_to comparator, class:"mx-[10px] my-[10px]" do %>
<div class="max-w-[245px] md:max-w-[220px] mdlg:max-w-[235px]">
  <div class="max-w-full max-h-[150px] w-full h-[150px]">
    <%= image_tag comparator.illustration, class: "w-full h-full object-cover rounded-md" %>
  </div>
  <div class="font-medium text-[#bbbac0] flex flex-row items-center text-[12px] mt-[25px]">
    <p class="mr-[7px]"><%= comparator.author %></p>
    <span class="w-[15px] h-[3px] bg-[#bbbac0] block rounded-full"></span>
    <p class="mx-[7px]"><%= l comparator.updated_at, :format => :short %></p>
  </div>
  <p class="mt-[10px] text-[#292a40] font-bold text-[20px]"><%= comparator.title%></p>
</div>
<% end %>

app/views/comparator_posts/_three_comparators.html.erb
<div class="flex flex-wrap justify-around md:justify-start">
   <% comparators.each do |comparator| %>
    <%= render partial: "comparator_posts/little_comparator", locals: {comparator: comparator }%>
  <% end %>
</div>

app/views/comparator_posts/index.html.erb
<div class="mb-[25px] w-full mt-[25px]">
  <div class="max-w-full max-h-[450px] w-full h-[450px]">
    <%= image_tag @comparator.illustration, class: "w-full h-full object-cover rounded-md" %>
  </div>
  <div class="mt-[15px]">
    <div class="font-medium text-[#bbbac0] flex flex-row items-center text-[13px] md:text-[15px] text-center">
      <p class="mr-[7px]"><%= @comparator.author %></p>
      <span class="w-[15px] h-[3px] bg-[#bbbac0] block rounded-full"></span>
      <p class="mx-[7px]"><%= l @comparator.updated_at, :format => :short %></p>
    </div>
    <p class="mt-[15px] text-[#292a40] font-bold text-3xl md:text-[40px]"><%= @comparator.title%></p>
  </div>
  <div class="my-[15px] post-content">
    <%= raw @comparator.body %>
  </div>
  <div class="mt-[45px]">
    <p class="title">Tu as apprécié cet article ?</p>
    <p class="mt-[10px]">Si tu souhaites nous soutenir, cela ce passe <%= link_to "juste ici, sur notre page de soutien.", support_path, class: "underline" %></p>
    <p class="mt-[10px] mb-[15px]">N'hésites pas à partager cet article sur les réseaux sociaux. Cela contribue à nous aider et à nous soutenir pour continuer notre aventure.</p>
    <%= render partial: "layouts/social_medias" %>
  </div>
</div>

app/views/comparator_posts/random.html.erb
<div class="pt-[20px]" data-turbo="false">
  <p class="title">Découvres une comparaison aléatoire</p>
  <p class="text-right underline mb-[25px]"><%= link_to "Une autre comparaison !", comparaison_random_path %></p>
  <%= render partial: "comparator_posts/comparator", locals: { comparator: @comparator } %>
</div>

app/views/comparator_posts/show.html.erb
<div class="pt-[20px]">
    <p class="title mb-[25px]">Retrouve toutes nos comparaisons</p>
    <%= render partial: "comparator_posts/comparators", locals: { comparators: @comparators } %>
    <%= paginate @comparators, window: 1 %>
</div>

app/views/layouts/_footer.html.erb
<footer class="bg-[#292a40] min-h-[100px] p-[15px] mt-[40px] text-[#f6f4f0] flex flex-col items-center">
  <p class="font-black text-center text-[30px]"><%= link_to "Le Versus", root_path %></p>
  <div class="flex flex-row items-center justify-around max-w-[500px] w-full flex-wrap my-[10px]">
    <p class="my-[8px]"><%= link_to "À propos",  about_path %></p>
    <p class="my-[8px]"><%= link_to "Contact",  contact_path %></p>
    <p class="my-[8px]"><%= link_to "Soutenez-nous !",  support_path %></p>
    <p class="my-[8px]"><%= link_to "CGU - Mention Légale",  legal_path %></p>
  </div>
  <div class="mt-[5px] mb-[10px]">
    <%= render partial: "layouts/social_medias" %>
  </div>
  <!--- Add donation button --->
  <p class="text-[#ccc] mt-[10px]">Copyright © <%= DateTime.current.year %> Le Versus</p>
</footer>

app/views/layouts/_header.html.erb
<header class="flex flex-col items-center justify-center w-full mt-[20px] px-[15px] pt-[15px]">
  <div class="flex flex-row items-center justify-center mb-[25px]">
    <p class="text-[45px] font-black text-center text-[#292a40]"><%= link_to "Le Versus", root_path %></p>
  </div>
  
  <div class="flex flex-row items-center justify-around flex-wrap w-full max-w-[700px] py-0 px-[15px] border-b-[3px] border-[#c6c6c6]">
    <p class="p-header-link <%= request.fullpath == root_path ? "p-header-link-active" : "" %>"><%= link_to "Accueil", root_path, class: "" %> </p>
    <p class="p-header-link <%= request.fullpath == comparaisons_path ? "p-header-link-active" : "" %>"><%= link_to "Nouveautés", comparaisons_path, class: "" %> </p>
    <p class="p-header-link <%= request.fullpath == comparaison_random_path ? "p-header-link-active" : "" %>"><%= link_to "Aléatoires", comparaison_random_path, class: "", data: {turbo: "false"} %> </p>
    <p class="p-header-link <%= request.fullpath == support_path ? "p-header-link-active" : "" %>"><%= link_to "Soutenez-nous", support_path, class: "" %> </p>
    <p class="p-header-link <%= request.fullpath == about_path ? "p-header-link-active" : "" %>"><%= link_to "À propos", about_path, class: "" %> </p>
  </div>
</header>

app/views/layouts/_social_medias.html.erb
<div class="flex flex-row flex-wrap items-center justify-center">
  <%= link_to "https://twitter.com", target: "_blank", class: "mx-[15px]" do %>
    <%= image_tag "rs/twitter.svg", class: "w-[43px]"%>
  <% end %>

  <%= link_to "https://instagram.com", target: "_blank", class: "mx-[15px]" do %>
    <%= image_tag "rs/instagram.svg", class: "w-[43px]"%>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Le Versus - Premier site de comparaison - Satire, humoristique</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="">
    <div class="notice-alert-container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= render "layouts/header" %>
    <main class="container flex max-w-[800px] items-center justify-center mx-auto px-[15px]">
      <%= yield %>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/static_pages/about.html.erb
<div class="pt-[20px] w-full h-full min-h-[50vh]">
  <h2 class="title">Le Versus, c'est quoi ?</h1>
  <p class="my-[5px]">Site Web <span class="font-medium">humoristique</span> créé en 2022, Le Versus cherche à créer du contenu <span class="font-medium">divertissant</span> (parfois sous fond de vérités) et <span class="font-medium">agréable</span>.</p>
  <p class="my-[5px]">Le Versus ne cherche pas à nuire ou autres, mais simplement à faire <span class="font-medium">rire</span> ses lecteurs à travers des comparaisons <span class="font-medium">drôles</span> et les plus respectueuses possible.</p>
  <p class="my-[5px]">Si tu <span class="font-medium">apprécies</span> Le Versus, penses à nous <span class="font-medium underline"><%= link_to "soutenir", support_path%></span> pour faire perdurer notre projet et nous aider à grandir.</p>
  
  <h2 class="title mt-[30px]">L'équipe</h2>
  <p class="mt-[5px] text-[8px] italic">Une grosse équipe de 1, ca fait du monde dans les réunions 😅</p>
  <div class="flex flex-col mt-[20px] p-[20px]">
    <div class="flex flex-col sm:flex-row items-center justify-center">
      <div class="h-[100px] max-w-[100px] w-full rounded-sm">
        <%= image_tag "about/valentin.jpg", alt: "La photo de Valentin, Fondateur et créateur de contenu", class: "h-full rounded-full object-cover"%>
      </div>
      <div class="mt-[20px]  sm:mt-[0px] ml-[0px] sm:ml-[30px] text-justify">
        <p class="font-medium text-[18px] mb-[10px] text-[#292a40] text-center sm:text-left"><%= link_to "Valentin BOUT", "https://www.boutvalentin.com", target: "_blank"%></p>
        <p class="mb-[7px]">Passionné de sport (Beaucoup d'escalade 🧗🏻‍♂️, de la rando 🥾, de la callisthénie en extérieur 💪, et plein d'autres encore 🏄🏻‍♂️, 🏂, 🚣🏻‍♂️, ... 🗺) et de la nature 🍃.</p>
        <p class="mb-[7px]">Fondateur de <%= link_to "Le Versus", root_path, class: "underline" %> et d'autres projet innovant, j'aspire à  partager mes trouvailles et ce que je sais faire (ou pense) pour aider les autres 🤝.</p>
        <p class="mb-[7px]">À travers <%= link_to "Le Versus", root_path, class: "underline" %>, j'écris et vous partage ce qui m'amuse, sans filtre pour rester le plus honnete 😇</p>
      </div>
    </div>
  </div>
  <p class="mt-[5px] text-[8px] italic">Même si je suis tout seul, je parle avec "nous" tous le temps car c'est vachement plus classe. 😂</p>


  <h2 class="title mt-[30px]">Pourquoi Le Versus ?</h2>
  <div>
    <p class="my-[5px]">
    Le Versus, c'est une idée toute jeune née en septembre 2022 (dans la superbe ville de Lille). Du haut de mon vénérable âge de 21 ans (un jeunot pour certain, un vieillard pour d’autre 😉), je suis née et j’ai grandi dans l’age d’or d’internet et des nouvelles technologies.</p> 
    <p class="my-[5px]">Malheureusement, je ne me retrouve pas vraiment dans le “journalisme” moderne. Les émissions anxiogènes a répétition, la survente de la peur et les titres racoleurs 🤯(et autres procédés) ne sont pas réellement m’ont dada.</p> 
    <p class="my-[5px]">Je me suis alors demandé ce que je souhaiterais lire, quotidiennement, pour me détendre et parfois pour soulever quelques sujets de fond. Je souhaitais créer un média libre, indépendant, gratuit (et sans pub) qui repose à 100 % sur ses utilisateurs et surtout un média sans prise de tête. Et paf, Le Versus est né de ce constat 🛫.</p>
  </div>

  <h2 class="title mt-[30px]">Et le but dans tout ça ?</h2>
  <p class="my-[5px]">Je ne vous ferai pas de grands discours sur mes ambitions sur le long terme et autres conneries que je ne tiendrais pas. Le but premier avec Le Versus et de vous faire rire et que vous vous amusiez à lire les articles que je peux écrire et partager. Je ne cherche pas à révolutionner le monde ou à devenir le prochain Jeff Bezos avec Le Versus, même si ça ferait toujours plaisir 😂.</p>

  <h2 class="title mt-[30px]">Une question ? Une remarque ?</h2>
  <p class="my-[5px]">Je me ferai un plaisir de discuter avec vous à travers les différents moyen de communication présent sur la page <%=link_to "contact", contact_path, class:"underline" %> du site.</p>
</div>

app/views/static_pages/contact.html.erb
<div class="pt-[20px] w-full h-full min-h-[50vh]">
  <p class="title">Nous contacter</p>
  <p class="mt-[15px]">Nous sommes toujours prêt à discuter avec toi.</p>

  <p class="font-medium mt-[10px] text-[17px]">Une idée, une envie à nous partager ? Un mot doux à susurrer ? </p>
  <p class="font-medium mt-[10px] text-[18px]">N'hésitez pas à nous contacter sur notre email <%= link_to "contact@leversus.com", "mailto:contact@leversus.com", class: "underline font-[600]" %></p>

  <p class="mt-[30px] mb-[20px]">Si tu préféres, nous sommes aussi sur les réseaux sociaux :</p>
  <%= render partial: "layouts/social_medias" %>
  <p class="mt-[40px]">
  Dans tous les cas, comme dirait guethenoc : 
  </p>
  <div class="flex flex-col items-center justify-center my-[10px]">
    <%= image_tag "kaamelott-guethenoc.gif", class: "rounded-md"%>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="pt-[20px]">
  <%= render partial: "comparator_posts/comparator", locals: { comparator: @comparators.first } %>
  <p class="title mb-[15px]">À la une</p>
  <% if @comparators[1..].empty? %>
    <p class="">Il n'y a pas encore d'autres articles disponibles... Patience, cela arrive !</p>
  <% end %>
  <%= render partial: "comparator_posts/three_comparators", locals: { comparators: @comparators[1..] } %>
  <p class="title my-[15px]">Le Versus, c'est quoi ?</p>
  <div class="text-justify font-light">
  <p class="my-[5px]">Site Web <span class="font-medium">humoristique</span> créé en 2022, Le Versus cherche à créer du contenu <span class="font-medium">divertissant</span> (parfois sous fond de vérités) et <span class="font-medium">agréable</span>.</p>
  <p class="my-[5px]">Le Versus ne cherche pas à nuire ou autres, mais simplement à faire <span class="font-medium">rire</span> ses lecteurs à travers des comparaisons <span class="font-medium">drôles</span> et les plus respectueuses possible.</p>
  <p class="my-[5px]">Si tu <span class="font-medium">apprécies</span> Le Versus, penses à nous <span class="font-medium underline"><%= link_to "soutenir", support_path%></span> pour faire perdurer notre projet et nous aider à grandir.</p>
  <p class="my-[5px]">Si tu veux en <span class="font-medium">savoir plus</span> sur Le Versus, consulte notre page <span class="font-medium underline"><%= link_to "À propos", support_path%></span>. Tu y trouveras plein d'information sur notre projet et sur ce que l'on fait.</p>
  
  </div>
  <p class="title my-[15px]">Vous appréciez Le Versus ? Alors soutenez-nous !</p>
  <p class="my-[5px]">Le Versus <span class="font-medium">dépend</span> entièrement <span class="font-medium">de vous et de vos soutiens !</span></p>
  <p class="my-[5px]">Il existe plusieurs facon de nous soutenirs et nous expliquons tous <span class="font-medium underline"><%= link_to "ça en détail sur notre page",  support_path %></span> dédié!</p>
</div>

app/views/static_pages/settings.html.erb
<p>
Paramètres
</p>

app/views/static_pages/support.html.erb
<div class="pt-[20px] w-full">
  <h1 class="title">Comment nous soutenir ?</h1>
  <p class="mt-[10px] text-justifiy">Il existe plusieurs manière de nous soutenir dans notres projets (et ceux à venir).</p>
  <p class="mt-[10px] text-justifiy">Nous sommes un 'média' indépendant qui est en réalité dépendant de vos soutiens pour continuer à vivre. Si vous apréciez nos comparaisons, notre projet ou plus, n'hésitez pas à choisir la manière qui vous convient le mieux pour vous soutenir.</p>

  <div class="mt-[20px]" id="tip">
    <h3 class="subtitle">La manière la plus simple : nous soutenir via les plateformes de 'Tip'</h3>
    <p class="mt-[10px] text-justifiy">Que ce soit à travers 1 euros ou plus, chacun de vos dons nous aident à faire perdurer notre projet au fil des années.</p>
    <div class="flex flex-row flex-wrap items-center justify-around mt-[45px] mb-[30px]">
      <% @supports.each do |support| %>
        <%= render partial: "supports/support", locals: {support: support} %>
      <% end %>
    </div>
  </div>

   <div class="mt-[30px]" id="prop_article">
    <h3 class="subtitle">Une autre manière : nous proposer des articles</h3>
    <p class="mt-[10px] text-justifiy">Il peut-être compliqué de nous soutenir financièrement pour de nombreuses raisons. Malgrés tout, vous pouvez nous soutenir différement en nous proposant des articles.</p>

    <p class="mt-[10px] text-justify">Pour nous proposer un article, rien de plus simple. Il suffit de nous envoyer un mail sur l'adresse mail <%= link_to "contact@leversus.com", "mailto:contact@leversus.com", class: "font-medium" %> et d'écrire l'article dans le corps de votre email. Vous pouvez avant ou après l'article dans votre mail nous parler de vous (Nom, Prénom, Année de naissance, Pseudonyme pour la publication et autres). Si nous acceptons votre article (dans l'état, hors correction orthographique, grammaticale ou autres), nous publions votre article sur le site web. Avant de nous proposer un article, il est très important de lire les CGU (section proposition d'article) afin de connaître vos droits et les notres.</p>

    <p class="mt-[10px] text-justify">Il est important de noter que nous n'acceptons aucune proposition d'article en pièce jointe (pour des raisons de sécurité). Toute propostion devra donc être rédigé dans le corps de l'email comme indiqué ci-dessus.</p>

    <p class="mt-[10px] text-justify">N'ayez pas peur de nous proposer vos idées ou vos articles et ne désesperait pas si nous n'acceptons pas plusieurs de vos articles. Votre participation nous fait déjà chaud au coeur et nous vous en remercions très fort, que votre article sois accepté ou non ❤️.</p>
    </div>

  <div class="mt-[30px]" id="share">
    <h3 class="subtitle">La dernière mais pas des moindres : partager notre site et nos comparaisons</h3>
    <p class="mt-[10px] text-justifiy">C'est probablement le moyen le plus simple pour nous soutenir. Partager nos comparaisons et notre sites à vos amis, collégues et plus si vous le souhaitez à travers tous les moyens que vous voulez.</p>
    <p class="mt-[10px] text-justifiy">Nous vous proposons une liste ci-dessous de réseaux sociaux sur lesquels vous pouvez nous suivre et ainsi partager nos articles (et être tenu au courant des nouvelles publications 😉).</p>
    <div class="mt-[25px]">
      <%= render partial: "layouts/social_medias" %>
    </div>
  </div>
</div>

app/views/supports/_support.html.erb
<%= link_to support.link, target: "_blank", class: "m-[14px]" do %>
<div class="active:scale-95 duration-100 text-center bg-[#fff] rounded-md p-3 max-w-[200px] flex flex-col items-center justify-between min-h-[230px]">
  <p class="font-medium text-[18px]"><%= support.title %></p>
  <%= image_tag support.illustration, class: "max-w-[150px] my-[20px] max-h-[50px]" %>
  <p class="font-light"><%= support.body %></p>
</div>
<% end %>